on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: cachix/install-nix-action@v17
      # Cherry-pick #178206 to master:
      # https://github.com/NixOS/nixpkgs/compare/master...024136c8498fb043d2c7728fd5485288684ad3a6
      - run: nix-build -A cmakeMinimal https://github.com/NixOS/nixpkgs/archive/024136c8498fb043d2c7728fd5485288684ad3a6.tar.gz
